### ISSUE TITLE
On registration, it thorws error to webpage

### ISSUE THREAD

**Issue by sahilrajput03** [r1/Full-Login-Dashboard#2]
![image](https://user-images.githubusercontent.com/31458531/84151908-9d9c7100-aa81-11ea-9ec5-5303f89f27ce.png)

**Comment by r1** [comment]
Did you npm install? Looks like a package might be installed.

**Comment by sahilrajput03** [comment]
Yes, I did.

**Comment by sahilrajput03** [comment]
I guess, it was saying because of empty group object. Fixed it and now its working.
![image](https://user-images.githubusercontent.com/31458531/84261766-f62f4500-ab39-11ea-97ec-f483d0c07239.png)
Its awesome project.

**Comment by sahilrajput03** [comment]
Still, propblem is it itn't fetching the group property at all from the frontend. What node version did you use to run the project? I still can't register a new user via the frontend. 
May be if I use the same version of node as you used could help. Could you check your working version node with this project ?

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/84264555-0564c180-ab3f-11ea-8287-b78d7c5c0173.png)
I tried with this version.
